<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'order' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'product' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::Login'], [], [['text', '/user']], [], []],
    'app_get_orders' => [[], ['_controller' => 'App\\Controller\\OrderController::getOrders'], [], [['text', '/order/getOrders']], [], []],
    'app_get_order' => [[], ['_controller' => 'App\\Controller\\OrderController::getOrder'], [], [['text', '/order/getOrder']], [], []],
];
